export const DialogType = {
  AuditLog: "Audit Log",
  Categories: "Categories",
  PriceInteligence: "PriceInteligence",
  Checklist: "Checklist",
  WorkPlanUpload: "WorkPlanUpload",
  AddTicket: "AddTicket",
  ActivityUpload: "ActivityUpload",
  SspUpload: "SspUpload",
  SspApproveModal: "SspApproveModal",
  SuccessModal: "SuccessModal",
  FundSuccessModal: "FundSuccessModal",
  PreventionModal: "PreventionModal",
  AssestAction: "AssestAction",
  FundRequestModal: "FundRequestModal",
  StateModal: "StateModal",
  FundRequstSummaryModal: "FundRequstSummaryModal",
  StakeholderModal: "StakeholderModal",
  ProjectObjectiveModal: "ProjectObjectiveModal",
  ConsortiumModal: "ConsortiumModal",
  ProjectUploadModal: "ProjectUploadModal",
  ProjectDetailsUploadModal: "ProjectDetailsUploadModal",
  EditUser: "EditUser",
  AssingRoleToUser: "AssingRoleToUser",
  AddPermissionToRole: "AddPermissionToRole",
  SspSubmitModal: "SspSubmitModal",
  AddStock: "AddStock",
  AddTeamMenbers: "AddTeamMenbers",
  ExpenditureModal: "ExpenditureModal",
  ConsultancyApplicationSuccess: "ConsultancyApplicationSuccess",
  SubGrantDocumentUpload: "SubGrantDocumentUpload",
  AddFundingSource: "AddFundingSource",
  AddBeneficiaries: "AddBeneficiaries",
  AddDocumentTypes: "AddDocumentTypes",
  AddPartners: "AddPartners",
  AddRiskCategory: "AddRiskCategory",
  AddInterventionArea: "AddInterventionArea",
  AddSupervisionCategory: "AddSupervisionCategory",
  AddFacility: "AddFacility",
  AddAssetConditions: "AddAssetConditions",
  AddAssetTypes: "AddAssetTypes",
  AddCategories: "AddCategories",
  AddDepartments: "AddDepartments",
  AddFinancialYear: "AddFinancialYear",
  AddItems: "AddItems",
  AddMarketPrice: "AddMarketPrice",
  AddNewItems: "AddNewItems",
  AddLocations: "AddLocations",
  AddLots: "AddLots",
  AddSolicitation: "AddSolicitation",
  AddPrequalificationCategory: "AddPrequalificationCategory",
  AddPrequalificationCriteria: "AddPrequalificationCriteria",
  AddQuestionairs: "AddQuestionairs",
  AddCostCategory: "AddCostCategories",
  AddBudgetLine: "AddBudgetLine",
  AddCostInput: "AddCostInput",
  AddCostGrouping: "AddCostGrouping",
  AddFcoNumber: "AddFcoNumber",
  AddProjectClasses: "AddProjectClasses",
  AddChartsOfAccounts: "AddChartsOfAccounts",
  ProcurementUploadModal: "ProcurementUploadModal",
  HrSuccessModal: "HrSuccessModal",
  ApprovalModal: "ApprovalModal",
  FeedbackModal: "FeedbackModal",
  ActivityTrackerModal: "ActivityTrackerModal",
  AddNewRoleModal: "AddNewRoleModal",
  AddSupervisionCriteria: "AddSupervisionCriteria",
  FundRequestBreakdown: "FundRequestBreakdown",
  ChangeRiskStatusModal: "ChangeRiskStatusModal",
  ChangeProjectStatusModal: "ChangeProjectStatusModal",
  AddPosition: "AddPosition",
  AddGrade: "AddGrade",
  AddLevel: "AddLevel",
  AddAssetClassification: "AddAssetClassification",
  ChangeWorkPlanStatusModal: "ChangeWorkPlanStatusModal",
  ChangeProcurementTrackerStatusModal: "ChangeProcurementTrackerStatusModal",
  ChangeProcurementTrackerRemarkModal: "ChangeProcurementTrackerRemarkModal",
  AssignToModal: "AssignToModal",
  EditValue: "EditValue",

  NewLeave: "NewLeave",

  ACTIVITY_PLAN_STATUS_MODAL: "ACTIVITY_PLAN_STATUS_MODAL",

  // GRANTS
  ADD_OBLIGATION_MODAL: "ADD_OBLIGATION_MODAL",
  SUBGRANT_MANUAL_SUB_UPLOAD: "SUBGRANT_MANUAL_SUB_UPLOAD",
  ADD_PRE_AWARD_QUESTION_MODAL: "ADD_PRE_AWARD_QUESTION_MODAL",
  MODIFY_GRANT: "MODIFY_GRANT",

  PREFERRED_CONSULTANT_MODAL: "PREFERRED_CONSULTANT_MODAL",

  // NEW LIST
  DOCUMENT_UPLOADS: "DOCUMENT_UPLOADS",

  // HR
  CREATE_INTERVIEW: "CREATE INTERVIEW",
  CREATE_GOALS: "CREATE GOALS",

  PAY_ADVICE: "PAY ADVICE",
  COPY_ACTIVITIES: "COPY ACTIVITIES",
  
  // Fund Request Workflow
  FundRequestApproval: "FundRequestApproval",
  FundRequestReject: "FundRequestReject",
  FundRequestSignature: "FundRequestSignature",
};

export const largeDailogScreen = {
  width: "max-w-6xl",
  height: "max-h-[700px]",
};

export const mediumDailogScreen = {
  width: "max-w-2xl",
  height: "max-h-[700px]",
};

// max-w-6xl max-h-[700px]
