export const Countries = [
  { label: "Lesotho", value: "Lesotho" },
  { label: "Swaziland", value: "Swaziland" },
  { label: "Botswana", value: "Botswana" },
  { label: "Namibia", value: "Namibia" },
  { label: "South Africa", value: "South Africa" },
  { label: "Benin", value: "Benin" },
  { label: "Liberia", value: "Liberia" },
  { label: "Saint Helena", value: "Saint Helena" },
  { label: "Burkina Faso", value: "Burkina Faso" },
  { label: "Gambia", value: "Gambia" },
  { label: "Mali", value: "Mali" },
  { label: "Ghana", value: "Ghana" },
  { label: "Mauritania", value: "Mauritania" },
  { label: "Senegal", value: "Senegal" },
  { label: "Cape Verde", value: "Cape Verde" },
  { label: "Cote D'ivoire", value: "Cote D'ivoire" },
  { label: "Guinea", value: "Guinea" },
  { label: "Niger", value: "Niger" },
  { label: "Sierra Leone", value: "Sierra Leone" },
  { label: "Guinea-Bissau", value: "Guinea-Bissau" },
  { label: "Nigeria", value: "Nigeria" },
  { label: "Togo", value: "Togo" },
];
